version: '3'

services:

  web:
    build: ./web
    restart: always
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ./app:/var/www/html
      - ./web/site.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${APACHE2_PORT}:80
    working_dir: /var/www/html
    
  composer:
    image: composer:2.4
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    command: composer install --ignore-platform-reqs --no-scripts

  db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/00-test-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spa_crud_db
    ports:
      - ${MYSQL_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password

  test:
    volumes:
      - ./app:/var/www/html
      - /var/www/html/bootstrap/cache/
    build:
      context: .
      dockerfile: test.dockerfile
    working_dir: /var/www/html
    command: ['bash', '-c', 'php artisan optimize --env=testing && php artisan migrate:fresh --seed && php artisan db:fake 10 && ./vendor/bin/phpunit']
